pipeline {
    agent any
    stages {
        stage('Clean Up') { // This will clean up anythin we run before and make sure nothing is persistent
            steps {
                deleteDir()
            }
        }
        stage('Clone Repo') {
            steps {
                sh 'git clone https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                dir('simple-java-maven-app') { // That is the current directory and it's persistent allong the stage
                    sh "sed -i 's/3.8.6/3.6.3/g' pom.xml" // That fixes a build error
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn test'
                }
            }
        }
    }
}
