pipeline {
    agent any

    parameters {
        booleanParam(defaultValue: false, description: 'Enable servicce?', name: 'myBoolean')
    }

    stages {
        stage('Demo') {
            steps {
                script {
                    if (params.myBoolean == false) {
                        currentBuild.result = 'SUCCESS'
                        return
                    }
                    else {
                        currentBuild.result = 'FAILURE'
                        return 'boleanParam is set to: TRUE'
                    }
                }
            }
        }
    }
}
